<?php
return [
    "free"=>[
        "search"=>[
            "availableHistory"=>7+1+30+30
        ]
    ],
    "silver"=>[
        "search"=>[
            "availableHistory"=>30+1,
        ]
    ],
    "gold"=>[
        "search"=>[
            "availableHistory"=>30*3+1,
        ]
    ],
    "platinum"=>[
        "search"=>[
            "availableHistory"=>30*6+1,
        ]
    ],
    "diamond"=>[
        "search"=>[
            "availableHistory"=>30*12+1,
        ]
    ]

];
